name: CI

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.08.1
          - 4.09.1
          - 4.10.2
          - 4.11.2
          - 4.12.0
        include:
          - { os: macos-latest, ocaml-version: 4.12.0 }
          - { os: windows-latest, ocaml-version: 4.12.0 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install Dune
        run: opam install dune --yes

      - name: Install OPAM Dependencies
        run: |
          opam exec -- dune build || true
          opam install . --yes --deps-only --with-doc --with-test
        ## FIXME: The caught failure of dune build is here to mitigate #4487.

      - name: Try Building
        run: opam exec -- make build

      - name: Try Building Documentation
        run: opam exec -- make doc

      - name: Run Tests
        run: opam exec -- make test

      - name: Try Installing
        run: opam exec -- make install

      - name: Try Uninstalling
        run: opam exec -- make uninstall

      - name: Try Cleaning
        run: opam exec -- make clean

      - name: Generate Documentation for Auto-Deployment
        run: opam exec -- make doc
        if: runner.os == 'Linux' && matrix.ocaml-version == '4.10.2' && github.event_name == 'push'

      - name: Auto-Deploy Documentation
        uses: Niols/deploy-odoc-action@main
        with:
          GENERATED_DOC_DIR: doc/
        if: runner.os == 'Linux' && matrix.ocaml-version == '4.10.2' && github.event_name == 'push'
