name: CI

on: push

defaults:
  run:
    shell: bash --login -e {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install OCaml & OPAM
        run: sudo apt-get install ocaml opam

      - name: Initialise OPAM
        run: opam init --auto-setup --compiler=ocaml-system

      - name: Install Dune
        run: opam install -y dune

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: opam install -y odoc menhir $(dune external-lib-deps @all | sed -n 's|- \(.*\)\..*|\1|p')

      - name: Try Building
        run: make build

      - name: Try Building Documentation
        run: make doc

      - name: Run Tests
        run: make test

      - name: Try Installing
        run: make install

      - name: Try Uninstalling
        run: make uninstall

      - name: Try Cleaning
        run: make clean
