name: CI

on: push

defaults:
  run:
    shell: bash --login -e {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install OCaml & OPAM
        run: sudo apt-get install ocaml opam

      - name: Initialise OPAM
        run: opam init --auto-setup --compiler=ocaml-system

      - name: Install Dune
        run: opam install -y dune

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: opam install -y odoc menhir $(dune external-lib-deps @all | sed -n 's|- \(.*\)\..*|\1|p')

      - name: Build
        run: make build

      - name: Build Documentation
        run: make doc

      - name: Run Test
        run: make test
