name: CI

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.08.1
          - 4.09.1
          - 4.10.2
          - 4.11.2
          - 4.12.0
        include:
          - { os: macos-latest, ocaml-version: 4.12.0 }
          - { os: windows-latest, ocaml-version: 4.12.0 }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install Dune
        run: opam install dune --yes

      - name: Install OPAM Dependencies
        run: |
          opam exec -- dune build || true
          opam install --yes menhir
          opam install . --yes --deps-only --with-doc --with-test
        ## FIXME: The caught failure of dune build is here to mitigate #4487.
        ## FIXME: The explicit installation of Menhir is here to mitigate #4486.

      - name: Try Building
        run: opam exec -- make build

      - name: Try Building Documentation
        run: opam exec -- make doc

      - name: Run Tests
        run: opam exec -- make test

      - name: Try Installing
        run: opam exec -- make install

      - name: Try Uninstalling
        run: opam exec -- make uninstall

      - name: Try Cleaning
        run: opam exec -- make clean
