name: CI

on: push

defaults:
  run:
    shell: bash --login -e {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install OCaml & OPAM
        run: sudo apt-get install ocaml opam

      - name: Initialise OPAM
        run: opam init --auto-setup --compiler=ocaml-system

      - name: Install Dune
        run: opam install -y dune

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: dune build 2>/dev/null || true; opam install -y menhir; opam install -y . --deps-only --with-doc --with-test
        ## FIXME: this line is a bit twisted because of two bugs:
        ## - The explicit installation of Menhir is here to mitigate #4486.
        ## - The caught failure (; instead of &&) of dune build is here to mitigate #4487.

      - name: Try Building
        run: make build

      - name: Try Building Documentation
        run: make doc

      - name: Run Tests
        run: make test

      - name: Try Installing
        run: make install

      - name: Try Uninstalling
        run: make uninstall

      - name: Try Cleaning
        run: make clean
